services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myeconomy
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    name: mysql

networks:
  finance_network:
    name: finance_app_network 